### PR TITLE
WIP: Feature/span classification

### PR DESCRIPTION
**Pull request by RobinRojowiec**
This feature branch introduces classification of arbitrary Spans, defined in the span groups in spacy Doc. 
They can be generated by e.g. a SpanRuler or any other component that generates Spans.

Either using `include_span` to include ALL spans for classification, or provide a list by using `înclude_span_groups` property in configuration.

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Hi, looking great already. Could you add a working code snippet and potentially also set the span classification to Doc.ents level?

**Comment by RobinRojowiec** [comment]
Great idea! Sure, I can add that as well.

**Comment by RobinRojowiec** [comment]
I added a working example, Wdyt? Would add similar for entites and unit test cases, then this PR is ready for merge.

**Comment by davidberenstein1957** [comment]
Hi @RobinRojowiec , sorry the end of year has been rather busy. I will take a look during the coming weekend.

**Pull request closed without merging**
